### PR TITLE
Updated metadate. Fixes #47

### LINKED ISSUE #47: Update your ms.prod and ms.technology metadata
WHY?
We're in the process of cleaning up our Product and Technology metadata as part of a larger APEX-wide effort to get the most value from our metadata. We've established a new taxonomy so that we'll be able to filter our content in a much more meaningful way using our BI tools/reports to gain customer insights.

BACKGROUND
We use metadata on Docs for reporting, discoverability of the content via search, and to drive aspects of the site experience. For reporting, metadata particularly drives the article and master rollup reports, as well as the APEX content dashboard. Metadata can also be queried directly through Kusto. If you do not set metadata correctly, your content will be misrepresented or underrepresented in reports, resulting in less information to help you understand and serve customers.

For the site experience, metadata helps drive the search API and site search behavior and generates various site features like scoped searches, code sample highlighting, and RSS feeds. If you do not set metadata fully and correctly, Docs site features will not work properly on your content, resulting in a subpar user experience.

ACTION
If there are any instances of ms.prod and ms.technology in your markdown topics, please remove them and apply the following settings to the "globalMetadata" object in your docfx.json file.

“ms.prod” : “console”

Please contact @kcpitt for more info

### PR DESCRIPTION
**Pull request by bitcrazed**

### CODE REVIEW

**Comment by bitcrazed** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/about-character-mode-applications.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/about-character-mode-applications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/about-character-mode-applications?branch=pr-en-us-53) |
[docs/addconsolealias.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/addconsolealias.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/addconsolealias?branch=pr-en-us-53) |
[docs/allocconsole.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/allocconsole.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/allocconsole?branch=pr-en-us-53) |
[docs/attachconsole.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/attachconsole.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/attachconsole?branch=pr-en-us-53) |
[docs/attaching-to-a-console.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/attaching-to-a-console.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/attaching-to-a-console?branch=pr-en-us-53) |
[docs/char-info-str.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/char-info-str.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/char-info-str?branch=pr-en-us-53) |
[docs/character-mode-applications.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/character-mode-applications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/character-mode-applications?branch=pr-en-us-53) |
[docs/clearing-the-screen.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/clearing-the-screen.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/clearing-the-screen?branch=pr-en-us-53) |
[docs/closing-a-console.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/closing-a-console.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/closing-a-console?branch=pr-en-us-53) |
[docs/console-aliases.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/console-aliases.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/console-aliases?branch=pr-en-us-53) |
[docs/console-application-issues.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/console-application-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/console-application-issues?branch=pr-en-us-53) |
[docs/console-buffer-security-and-access-rights.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/console-buffer-security-and-access-rights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/console-buffer-security-and-access-rights?branch=pr-en-us-53) |
[docs/console-code-pages.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/console-code-pages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/console-code-pages?branch=pr-en-us-53) |
[docs/console-control-handlers.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/console-control-handlers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/console-control-handlers?branch=pr-en-us-53) |
[docs/console-cursor-info-str.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/console-cursor-info-str.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/console-cursor-info-str?branch=pr-en-us-53) |
[docs/console-font-info-str.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/console-font-info-str.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/console-font-info-str?branch=pr-en-us-53) |
[docs/console-font-infoex.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/console-font-infoex.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/console-font-infoex?branch=pr-en-us-53) |
[docs/console-functions.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/console-functions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/console-functions?branch=pr-en-us-53) |
[docs/console-handles.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/console-handles.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/console-handles?branch=pr-en-us-53) |
[docs/console-history-info.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/console-history-info.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/console-history-info?branch=pr-en-us-53) |
[docs/console-input-buffer.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/console-input-buffer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/console-input-buffer?branch=pr-en-us-53) |
[docs/console-modes.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/console-modes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/console-modes?branch=pr-en-us-53) |
[docs/console-process-groups.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/console-process-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/console-process-groups?branch=pr-en-us-53) |
[docs/console-readconsole-control.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/console-readconsole-control.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/console-readconsole-control?branch=pr-en-us-53) |
[docs/console-reference.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/console-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/console-reference?branch=pr-en-us-53) |
[docs/console-screen-buffer-info-str.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/console-screen-buffer-info-str.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/console-screen-buffer-info-str?branch=pr-en-us-53) |
[docs/console-screen-buffer-infoex.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/console-screen-buffer-infoex.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/console-screen-buffer-infoex?branch=pr-en-us-53) |
[docs/console-screen-buffers.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/console-screen-buffers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/console-screen-buffers?branch=pr-en-us-53) |
[docs/console-selection-info-str.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/console-selection-info-str.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/console-selection-info-str?branch=pr-en-us-53) |
[docs/console-selection.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/console-selection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/console-selection?branch=pr-en-us-53) |
[docs/console-structures.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/console-structures.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/console-structures?branch=pr-en-us-53) |
[docs/console-virtual-terminal-sequences.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/console-virtual-terminal-sequences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences?branch=pr-en-us-53) |
[docs/console-winevents.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/console-winevents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/console-winevents?branch=pr-en-us-53) |
[docs/consoles.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/consoles.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/consoles?branch=pr-en-us-53) |
[docs/coord-str.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/coord-str.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/coord-str?branch=pr-en-us-53) |
[docs/createconsolescreenbuffer.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/createconsolescreenbuffer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/createconsolescreenbuffer?branch=pr-en-us-53) |
[docs/creation-of-a-console.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/creation-of-a-console.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/creation-of-a-console?branch=pr-en-us-53) |
[docs/ctrl-c-and-ctrl-break-signals.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/ctrl-c-and-ctrl-break-signals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/ctrl-c-and-ctrl-break-signals?branch=pr-en-us-53) |
[docs/ctrl-close-signal.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/ctrl-close-signal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/ctrl-close-signal?branch=pr-en-us-53) |
[docs/fillconsoleoutputattribute.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/fillconsoleoutputattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/fillconsoleoutputattribute?branch=pr-en-us-53) |
[docs/fillconsoleoutputcharacter.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/fillconsoleoutputcharacter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/fillconsoleoutputcharacter?branch=pr-en-us-53) |
[docs/flushconsoleinputbuffer.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/flushconsoleinputbuffer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/flushconsoleinputbuffer?branch=pr-en-us-53) |
[docs/focus-event-record-str.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/focus-event-record-str.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/focus-event-record-str?branch=pr-en-us-53) |
[docs/freeconsole.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/freeconsole.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/freeconsole?branch=pr-en-us-53) |
[docs/generateconsolectrlevent.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/generateconsolectrlevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/generateconsolectrlevent?branch=pr-en-us-53) |
[docs/getconsolealias.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/getconsolealias.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/getconsolealias?branch=pr-en-us-53) |
[docs/getconsolealiases.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/getconsolealiases.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/getconsolealiases?branch=pr-en-us-53) |
[docs/getconsolealiaseslength.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/getconsolealiaseslength.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/getconsolealiaseslength?branch=pr-en-us-53) |
[docs/getconsolealiasexes.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/getconsolealiasexes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/getconsolealiasexes?branch=pr-en-us-53) |
[docs/getconsolealiasexeslength.md](https://github.com/MicrosoftDocs/Console-Docs/blob/bitcrazed/1811-metadata-update/docs/getconsolealiasexeslength.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/console/getconsolealiasexeslength?branch=pr-en-us-53) |

This comment lists only the first 50 files in the pull request.
For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C11%5C8%5C5aa0b9b2-fff5-b93b-b200-e4f09975c769%5CPullRequest%5C201811082315061603-53%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=kFL1DWabVFOnONVelEzCDlvR9GygeRVhHqTJv%2F2FuS0%3D&st=2018-11-08T23%3A11%3A10Z&se=2018-12-09T23%3A16%3A10Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by msatranjr** [comment]
Maybe I missed it, but did you add the globalMetadata to the docfx?

**Comment by bitcrazed** [comment]
@msatranjr - didn't need to - ms.prod was already in there: https://github.com/MicrosoftDocs/Console-Docs/blob/master/docs/docfx.json#L37.

Does this look good to you?

**Comment by msatranjr** [comment]
Looks good

**Pull request merged**
