### PR TITLE
[BrokenLinksH2] Fixed the link path

### PR DESCRIPTION
**Pull request by v-sidlama**
Fixed the link

### CODE REVIEW

**Comment by DhurataJ** [comment]
@DCtheGeek - The C+E Skilling team is fixing broken links on docs.microsoft.com. This will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes/removals and does not change other content. This PR is ready for merge. Thank you!

**Comment by DCtheGeek** [comment]
> @DCtheGeek - The C+E Skilling team is fixing broken links on docs.microsoft.com. This will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes/removals and does not change other content. This PR is ready for merge. Thank you!

That's cool, but I don't own this content. :)

**Comment by DhurataJ** [comment]
> > @DCtheGeek - The C+E Skilling team is fixing broken links on docs.microsoft.com. This will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes/removals and does not change other content. This PR is ready for merge. Thank you!
> 
> That's cool, but I don't own this content. :)

Do you have any suggestions to whom I might be able to address this open PR. Thanks! :)

**Comment by DCtheGeek** [comment]
> > > @DCtheGeek - The C+E Skilling team is fixing broken links on docs.microsoft.com. This will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes/removals and does not change other content. This PR is ready for merge. Thank you!
> > 
> > 
> > That's cool, but I don't own this content. :)
> 
> Do you have any suggestions to whom I might be able to address this open PR. Thanks! :)

I'd try the author, @miniksa.

**Comment by DhurataJ** [comment]
@miniksa - I'd very much appreciate your timely review and merge this PR. Thanks!

**Pull request merged**
